### PR TITLE
Re frontend testing

### PR DESCRIPTION
**Pull request by danbourdier**
Spearheaded Jest and Enzyme for frontend testing/refactoring/ and continuity for future devs!

Screen Shot 2020-09-23 at 4 01 12 PM
Screen Shot 2020-09-23 at 4 01 26 PM

### CODE REVIEW

**Comment by isaac-owens** [comment]
- This looks really great @danbourdier  !  

Questions:
- Did you utilize TDD on this first test?  Does the test fail in the appropriate conditions? 

- Is there any documentation for new devs in the future that would be looking to add to this suite in the future for feature development and debugging?  

I'd be happy to layout out some conventions and best practices with you to keep this suite tight and clean for future use.

**Comment by danbourdier** [comment]
@isaac-owens For sure! So this does fail in the initial testing when I first ran the test and found there were errors for our styling loaders breaking in several areas (but still running our site!). Another basic test as seen above was if the shallow component was indeed truthy (this is another way to check if the component loads correctly after we identify it) I learned as soon as I did this that there were dependency issues which were resolved once I reversioned several packages to a more compatible version. As for your next question, yes! I am currently drafting up an additional section I can append to our current Readme for future devs to refer back to. After further parsing the documentation I can make my draft as intuitive as possible on not just use, but development of further tests as well!

**Comment by danbourdier** [comment]
> @isaac-owens For sure! So this does fail in the initial testing when I first ran the test and found there were errors for our styling loaders breaking in several areas (but still running our site!). Another basic test as seen above was if the shallow component was indeed truthy (this is another way to check if the component loads correctly after we identify it) I learned as soon as I did this that there were dependency issues which were resolved once I reversioned several packages to a more compatible version. As for your next question, yes! I am currently drafting up an additional section I can append to our current Readme for future devs to refer back to. After further parsing the documentation I can make my draft as intuitive as possible on not just use, but development of further tests as well!

Also I am currently working to get a card on trello created so that we may start collaborating on it! I will keep everyone updated on it

**Comment by khaliqzohaib92** [comment]
Hi Dan,

Great work in introducing tests I have reviewed all the file that has been changed to introduce it. So, I have the following suggestions:
- Will you please remove the commented code from the jest config file.
- Instead of enzyme you can use a react testing library because it is easy to test components with react testing library as compared to the enzyme and it is also recommended. I have not done much with the react testing library but will be looking forward to your thoughts on it!

Keep up the good work!!!

**Comment by danbourdier** [comment]
@khaliqzohaib92 
1. I can definitely remove the comments In the jest.config.file, the issue with that would be how it would inconvenience future devs that desire to have several options offered/ and explained to them with said comments of the auto-generated config file. And as we are doing this for continuity it might be more harmful than beneficial to DRY up code. I welcome further input on thoughts on this.

2. As for the react testing library I did perform research over the weekend and it seemed to create ease of future implementation for the purpose of somewhat DRYer code at the expense of laying out testing-id attrs for every single DOM element we want to test. RTL seems to better serve the purpose of e2e tests while we are currently running unit testing until we map out further goals. As for your experience with RTL I would love to learn your perspective on the library so I can learn more. Right now the biggest takeaway I got for the contrasting tech is that the speed and efficiency of creating mocks for children are not offered by RTL and Enzyme allows it. Since speed is currently an issue with our site It might take away from our current progress in application efficiency. I would love further input on your thoughts! This did give me the chance to take a deep dive on time I would not have had the time to explore in the past! Plus I felt this tech (given the direction of industry trends) would greatly benefit those to come with a skillset currently utilized by companies that adopted the testing utility (AirBnB).

**Comment by danbourdier** [comment]
@khaliqzohaib92 Before I forget! If we want to implement said testing I will need help in reconfiguring babel config, its environment presets, file transformations, and the pesky associated dependencies.

**Comment by khaliqzohaib92** [comment]
@danbourdier Sure, I would be happy to help.

**Comment by JGYaniv** [comment]
Hey Dan you just need to do a rebase before we can merge this. Looks great though, some much needed testing for the app!

**Pull request merged**
