### PR TITLE
Adding Privacy Link On Footer

### PR DESCRIPTION
**Pull request by yb0608**

### CODE REVIEW

**Review by JGYaniv — CHANGES_REQUESTED** [review]
Please only commit the lines that you changed, your linter has modified the entire file which makes it hard to read the PR and messes up our commit history/blame.

Did you change anything in app/javascript/components/SearchBar.js or was it just linting?

**Comment by yb0608** [comment]
> Please only commit the lines that you changed, your linter has modified the entire file which makes it hard to read the PR and messes up our commit history/blame.
> 
> Did you change anything in app/javascript/components/SearchBar.js or was it just linting?

I didn't change app/javascript/components/SearchBar.js for this card, it was just the linting.

**Comment by acheng08** [comment]
@JGYaniv Is there anything @yb0608 needs to do before we can merge the PR?

**Comment by JGYaniv** [comment]
I haven’t had a chance to look this week, but he just needs to revert the
changes in that file. It could be as simple as just copying the page from
dev and pasting into his branch.

**Review by Brian-Tutoria — CHANGES_REQUESTED** [review]
As Jonathan said before:
Please only commit the lines that you changed, your linter has modified the entire file which makes it hard to read the PR and messes up our commit history/blame.

Your system is changing single quotes to double quotes, as well as spacing.

**Pull request closed without merging**
