### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by xzwang93**
Fix:
Update Material UI Version: Volunteer's Profile
Update Material UI Version: Compose New Message Page

### CODE REVIEW

**Comment by xzwang93** [comment]
New to git but wondering if I am doing it correctly.

**Review by JGYaniv — CHANGES_REQUESTED** [review]
Resolve merge conflict please, this was previously merging into master but should have been merging in to nonpartisan09:feature/Material_UI_Changes_276

**Review by JGYaniv — APPROVED** [review]
LGTM, but should be reviewed by Andy

**Comment by acheng08** [comment]
Added @andysmitharng  to the reviewer list per Jonathan's comment above.

**Review by Brian-Tutoria — APPROVED** [review]
Looks good!

**Comment by acheng08** [comment]
Related Trello Cards: 

- https://trello.com/c/TWCW88yt/23-update-material-ui-version-volunteers-profile
- https://trello.com/c/NbQTbse5/24-update-material-ui-version-compose-new-message-page

**Review by Brian-Tutoria — CHANGES_REQUESTED** [review]
The vertical spacing of the volunteer's profile is off with the "Message User", stars, "Leave a comment", and "Submit review".

Also, Chrome shows the following warnings when the pages load:
Warning: Received `true` for a non-boolean attribute `primary`.
Warning: React does not recognize the `hintText` prop on a DOM element.
Warning: React does not recognize the `errorText` prop on a DOM element.
Warning: React does not recognize the `errorStyle` prop on a DOM element.
Warning: React does not recognize the `zDepth` prop on a DOM element.

**Comment by xzwang93** [comment]
7da88821d84287d017fb8b061364586
The spacing is fixed. 

zDepth (as well as some other warnings) doesn't seem to related to the cards of this message. I can fix zDepth, but just let you know that this line of code changing may not related to the message button.

I've already get those covered and they are under xzwang93/class_scheduler. Should I pull another pull request or I can just change update the file to the tree, and we can access the changes in this pull request?

**Review by Brian-Tutoria — APPROVED** [review]

**Comment by Brian-Tutoria** [comment]
Don't worry about the zDepth. Please commit with the new spacing though.

**Review by Brian-Tutoria — CHANGES_REQUESTED** [review]
@xzwang93 please commit your most recent changes for the vertical spacing.

**Review by Brian-Tutoria — APPROVED** [review]
Tested and the vertical alignment has been corrected.

**Pull request merged**
